
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searh-city-deployment
  labels:
    name: search-city-label
    app: search-city
spec:
  replicas: 3
  selector:
    matchLabels:
     name: search-city-pod
     app: search-city
  template:
    metadata:
      labels:
        name: search-city-pod
        app: search-city

    spec:
      containers:
      - name: search-city
        image: gcr.io/api-project-1072578278872/suggest-city:v1
        ports:
        - containerPort: 8080
