apiVersion: v1

kind: Service

metadata:
  name: search-city-service
  labels:
    app: search-city
    name: search-city-service

spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: search-city-pod
    app: search-city





